add list all venvs method and add is valid name conditional
dany2691/clipenv pull request #18
Opened 2019-10-07 02:45 UTC by valerybriz

2019-10-09 16:13 UTC, danvergara requested changes

2019-10-09 16:13 UTC, danvergara commented on clipenv/cli/commands.py
> +                all_vars = profile_file.read()
I thought you'd perform some regex on every row to retrieve all the environment variables, because, inside this kinda files there are many other config settings. For instance, the Anaconda configuration.

We must look for rows like this: export VARIABLE_NAME=VARIABLE_VALUE.

2019-10-09 16:13 UTC, danvergara commented on tests/test_cli.py
> +        assert False
If the condition next to the assert statement is false, the test will fail, otherwise, the test will pass. I'm not sure you're evaluating if the result of add_env_var is truthy or not None.

The example below would be easier to read and more pythonic:

```python
assert commands.add_env_var(...)
assert commands.add_env_var(...) is not None
assert variable_name in commands.list_all_env_vars(default_profile_file) 
```

2019-10-09 16:13 UTC, danvergara commented on tests/test_cli.py
> +            assert False
A more pythonic approach:

```python
assert not variable_name in commands.list_all_env_vars("non_existent_file")
```

2019-10-09 16:13 UTC, danvergara commented on tests/test_filesystem_utilities.py
> +    assert is_valid_var_name(wrong_var) is True
More pythonic:

```python
assert not is_valid_var_name(wrong_var)

assert is_valid_var_name(valid_var)
```

2019-10-09 16:22 UTC, valerybriz commented on clipenv/cli/commands.py
> +                all_vars = profile_file.read()
I agree, I'll add a more precise search on the file :)

2019-10-09 16:26 UTC, valerybriz commented on tests/test_cli.py
> +            assert False
good one :)

2019-10-09 16:27 UTC, valerybriz commented on tests/test_filesystem_utilities.py
> +    assert is_valid_var_name(wrong_var) is True
good :)

2019-10-09 21:47 UTC, valerybriz commented on tests/test_cli.py
> +        assert False
I changed this calls :)

2019-10-13 17:11 UTC, danvergara approved these changes

2019-10-13 17:11 UTC, merged